server:
  port: 80

api-prefix: /api

# yaml/yml 파일 - Thymeleaf 설정
thymeleaf:
  cache: false
  check-template-location: true
  prefix: classpath:/templates/
  suffix: .html
  enabled: true


spring:
  profiles:
    include: oauth # application-oauth.yaml ?? ??

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false   # Keep entities within method only
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Specify the batch size 100
