spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false


  data:
    mongodb:
#      uri: mongodb://admin:cp6zIfrAPtcogGSR@3.35.218.166:27017/etd?authSource=admin
      uri: mongodb://3.35.218.166:27017
      username: mongoAdmin
      password: cp6zIfrAPtcogGSR
      authentication-database: admin
      database: etd
