spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false


  data:
    mongodb:
#      uri: mongodb://admin:cp6zIfrAPtcogGSR@3.35.218.166:27017/etd?authSource=admin
      host: 3.35.218.166
      port: 27017
      database: easy-to-dedicate
      authentication-database: admin
      username: admin
      password: cp6zIfrAPtcogGSR
