spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false


  data:
    mongodb:
      uri: mongodb://admin:cp6zIfrAPtcogGSR@3.35.218.166:27017/easy-to-dedicate?authSource=admin
#      username: admin
#      password: cp6zIfrAPtcogGSR
