package io.goorm.etdservice.domain.games.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonNaming(PropertyNamingStrategies.UpperSnakeCaseStrategy.class)
public class PalworldOption {

    private Integer PLAYERS = 16;
    private Integer PORT=8211;
    private Integer PUID=1000;
    private Integer PGID=1000;
    private Boolean MULTITHREADING=false;
    private Boolean COMMUNITY=false;
    //    PUBLIC_IP=
//    PUBLIC_PORT=
    private String SERVER_NAME="palworld-server-docker by Thijs van Loef";
    private String SERVER_DESCRIPTION="palworld-server-docker by Thijs van Loef";
    private String SERVER_PASSWORD="worldofpals";
    private String ADMIN_PASSWORD="adminPasswordHere";
    private Boolean UPDATE_ON_BOOT=true;
    private Boolean RCON_ENABLED=true;
    private Integer RCON_PORT=25575;
    private Integer QUERY_PORT=27015;
//    BACKUP_ENABLED=true
//    DELETE_OLD_BACKUPS=false
//    OLD_BACKUP_DAYS=30
//    BACKUP_CRON_EXPRESSION=0 0 * * *
//    AUTO_UPDATE_ENABLED=false
//    AUTO_UPDATE_CRON_EXPRESSION=0 * * * *
//    AUTO_UPDATE_WARN_MINUTES=30
//    AUTO_REBOOT_ENABLED=false
//    AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE=false
//    AUTO_REBOOT_WARN_MINUTES=5
//    AUTO_REBOOT_CRON_EXPRESSION=0 0 * * *
//    ENABLE_PLAYER_LOGGING=true
//    PLAYER_LOGGING_POLL_PERIOD=5
    private String DIFFICULTY="None";
    private Float DAYTIME_SPEEDRATE= 1.000000F;
    private Float NIGHTTIME_SPEEDRATE= 1.000000F;
    private Float EXP_RATE= 1.000000F;
    private Float PAL_CAPTURE_RATE= 1.000000F;
    private Float PAL_SPAWN_NUM_RATE = 1.000000F;
    private Float PAL_DAMAGE_RATE_ATTACK = 1.000000F;
    private Float PAL_DAMAGE_RATE_DEFENSE = 1.000000F;

    private Float PLAYER_DAMAGE_RATE_ATTACK= 1.000000F;
    private Float PLAYER_DAMAGE_RATE_DEFENSE = 1.000000F;
    private Float PLAYER_STOMACH_DECREASE_RATE = 1.000000F;
    private Float PLAYER_STAMINA_DECREASE_RATE = 1.000000F;
    private Float PLAYER_AUTO_HP_REGEN_RATE = 1.000000F;
    private Float PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP = 1.000000F;
    private Float PAL_STOMACH_DECREASE_RATE = 1.000000F;
    private Float PAL_STAMINA_DECREASE_RATE = 1.000000F;
    private Float PAL_AUTO_HP_REGEN_RATE = 1.000000F;
    private Float PAL_AUTO_HP_REGEN_RATE_IN_SLEEP = 1.000000F;
    private Float BUILD_OBJECT_DAMAGE_RATE = 1.000000F;
    private Float BUILD_OBJECT_DETERIORATION_DAMAGE_RATE = 1.000000F;
    private Float COLLECTION_DROP_RATE = 1.000000F;
    private Float COLLECTION_OBJECT_HP_RATE = 1.000000F;
    private Float COLLECTION_OBJECT_RESPAWN_SPEED_RATE = 1.000000F;
    private Float ENEMY_DROP_ITEM_RATE = 1.000000F;
    private String DEATH_PENALTY= "All";
    private String ENABLE_PLAYER_TO_PLAYER_DAMAGE="False";
    private String ENABLE_FRIENDLY_FIRE="False";
    private String ENABLE_INVADER_ENEMY="True";
    private String ACTIVE_UNKO = "False";
    private String ENABLE_AIM_ASSIST_PAD="True";
    private String ENABLE_AIM_ASSIST_KEYBOARD="False";
    private Integer DROP_ITEM_MAX_NUM = 3000;
    private Integer DROP_ITEM_MAX_NUM_UNKO = 100;
    private Integer BASE_CAMP_MAX_NUM = 128;
    private Integer BASE_CAMP_WORKER_MAX_NUM = 15;
    private Float DROP_ITEM_ALIVE_MAX_HOURS = 1.000000F;
    private String AUTO_RESET_GUILD_NO_ONLINE_PLAYERS="False";
    private Float AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS= 72.00000F;
    private Integer GUILD_PLAYER_MAX_NUM = 20;
    private Float PAL_EGG_DEFAULT_HATCHING_TIME = 72.00000F;
    private Float WORK_SPEED_RATE= 1.000000F;
    private String IS_MULTIPLAY="False";
    private String IS_PVP = "False";
    private String CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP = "False";
    private String ENABLE_NON_LOGIN_PENALTY ="True";
    private String ENABLE_FAST_TRAVEL ="True";
    private String IS_START_LOCATION_SELECT_BY_MAP ="True";
    private String EXIST_PLAYER_AFTER_LOGOUT = "False";
    private String ENABLE_DEFENSE_OTHER_GUILD_PLAYER = "False";
    private Integer COOP_PLAYER_MAX_NUM=4;
    private String REGION="";
    private String USEAUTH = "True";
    private String BAN_LIST_URL="https://api.palworldgame.com/api/banlist.txt";
    private String SHOW_PLAYER_LIST = "True";
    @Builder
    public PalworldOption(Integer PLAYERS, Integer PORT, Integer PUID, Integer PGID, Boolean MULTITHREADING, Boolean COMMUNITY, String SERVER_NAME, String SERVER_DESCRIPTION, String SERVER_PASSWORD, String ADMIN_PASSWORD, Boolean UPDATE_ON_BOOT, Boolean RCON_ENABLED, Integer RCON_PORT, Integer QUERY_PORT, String DIFFICULTY, Float DAYTIME_SPEEDRATE, Float NIGHTTIME_SPEEDRATE, Float EXP_RATE, Float PAL_CAPTURE_RATE, Float PAL_SPAWN_NUM_RATE, Float PAL_DAMAGE_RATE_ATTACK, Float PAL_DAMAGE_RATE_DEFENSE, Float PLAYER_DAMAGE_RATE_ATTACK, Float PLAYER_DAMAGE_RATE_DEFENSE, Float PLAYER_STOMACH_DECREASE_RATE, Float PLAYER_STAMINA_DECREASE_RATE, Float PLAYER_AUTO_HP_REGEN_RATE, Float PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP, Float PAL_STOMACH_DECREASE_RATE, Float PAL_STAMINA_DECREASE_RATE, Float PAL_AUTO_HP_REGEN_RATE, Float PAL_AUTO_HP_REGEN_RATE_IN_SLEEP, Float BUILD_OBJECT_DAMAGE_RATE, Float BUILD_OBJECT_DETERIORATION_DAMAGE_RATE, Float COLLECTION_DROP_RATE, Float COLLECTION_OBJECT_HP_RATE, Float COLLECTION_OBJECT_RESPAWN_SPEED_RATE, Float ENEMY_DROP_ITEM_RATE, String DEATH_PENALTY, String ENABLE_PLAYER_TO_PLAYER_DAMAGE, String ENABLE_FRIENDLY_FIRE, String ENABLE_INVADER_ENEMY, String ACTIVE_UNKO, String ENABLE_AIM_ASSIST_PAD, String ENABLE_AIM_ASSIST_KEYBOARD, Integer DROP_ITEM_MAX_NUM, Integer DROP_ITEM_MAX_NUM_UNKO, Integer BASE_CAMP_MAX_NUM, Integer BASE_CAMP_WORKER_MAX_NUM, Float DROP_ITEM_ALIVE_MAX_HOURS, String AUTO_RESET_GUILD_NO_ONLINE_PLAYERS, Float AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS, Integer GUILD_PLAYER_MAX_NUM, Float PAL_EGG_DEFAULT_HATCHING_TIME, Float WORK_SPEED_RATE, String IS_MULTIPLAY, String IS_PVP, String CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP, String ENABLE_NON_LOGIN_PENALTY, String ENABLE_FAST_TRAVEL, String IS_START_LOCATION_SELECT_BY_MAP, String EXIST_PLAYER_AFTER_LOGOUT, String ENABLE_DEFENSE_OTHER_GUILD_PLAYER, Integer COOP_PLAYER_MAX_NUM, String REGION, String USEAUTH, String BAN_LIST_URL, String SHOW_PLAYER_LIST) {
        this.PLAYERS = PLAYERS;
        this.PORT = PORT;
        this.PUID = PUID;
        this.PGID = PGID;
        this.MULTITHREADING = MULTITHREADING;
        this.COMMUNITY = COMMUNITY;
        this.SERVER_NAME = SERVER_NAME;
        this.SERVER_DESCRIPTION = SERVER_DESCRIPTION;
        this.SERVER_PASSWORD = SERVER_PASSWORD;
        this.ADMIN_PASSWORD = ADMIN_PASSWORD;
        this.UPDATE_ON_BOOT = UPDATE_ON_BOOT;
        this.RCON_ENABLED = RCON_ENABLED;
        this.RCON_PORT = RCON_PORT;
        this.QUERY_PORT = QUERY_PORT;
        this.DIFFICULTY = DIFFICULTY;
        this.DAYTIME_SPEEDRATE = DAYTIME_SPEEDRATE;
        this.NIGHTTIME_SPEEDRATE = NIGHTTIME_SPEEDRATE;
        this.EXP_RATE = EXP_RATE;
        this.PAL_CAPTURE_RATE = PAL_CAPTURE_RATE;
        this.PAL_SPAWN_NUM_RATE = PAL_SPAWN_NUM_RATE;
        this.PAL_DAMAGE_RATE_ATTACK = PAL_DAMAGE_RATE_ATTACK;
        this.PAL_DAMAGE_RATE_DEFENSE = PAL_DAMAGE_RATE_DEFENSE;
        this.PLAYER_DAMAGE_RATE_ATTACK = PLAYER_DAMAGE_RATE_ATTACK;
        this.PLAYER_DAMAGE_RATE_DEFENSE = PLAYER_DAMAGE_RATE_DEFENSE;
        this.PLAYER_STOMACH_DECREASE_RATE = PLAYER_STOMACH_DECREASE_RATE;
        this.PLAYER_STAMINA_DECREASE_RATE = PLAYER_STAMINA_DECREASE_RATE;
        this.PLAYER_AUTO_HP_REGEN_RATE = PLAYER_AUTO_HP_REGEN_RATE;
        this.PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP = PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP;
        this.PAL_STOMACH_DECREASE_RATE = PAL_STOMACH_DECREASE_RATE;
        this.PAL_STAMINA_DECREASE_RATE = PAL_STAMINA_DECREASE_RATE;
        this.PAL_AUTO_HP_REGEN_RATE = PAL_AUTO_HP_REGEN_RATE;
        this.PAL_AUTO_HP_REGEN_RATE_IN_SLEEP = PAL_AUTO_HP_REGEN_RATE_IN_SLEEP;
        this.BUILD_OBJECT_DAMAGE_RATE = BUILD_OBJECT_DAMAGE_RATE;
        this.BUILD_OBJECT_DETERIORATION_DAMAGE_RATE = BUILD_OBJECT_DETERIORATION_DAMAGE_RATE;
        this.COLLECTION_DROP_RATE = COLLECTION_DROP_RATE;
        this.COLLECTION_OBJECT_HP_RATE = COLLECTION_OBJECT_HP_RATE;
        this.COLLECTION_OBJECT_RESPAWN_SPEED_RATE = COLLECTION_OBJECT_RESPAWN_SPEED_RATE;
        this.ENEMY_DROP_ITEM_RATE = ENEMY_DROP_ITEM_RATE;
        this.DEATH_PENALTY = DEATH_PENALTY;
        this.ENABLE_PLAYER_TO_PLAYER_DAMAGE = ENABLE_PLAYER_TO_PLAYER_DAMAGE;
        this.ENABLE_FRIENDLY_FIRE = ENABLE_FRIENDLY_FIRE;
        this.ENABLE_INVADER_ENEMY = ENABLE_INVADER_ENEMY;
        this.ACTIVE_UNKO = ACTIVE_UNKO;
        this.ENABLE_AIM_ASSIST_PAD = ENABLE_AIM_ASSIST_PAD;
        this.ENABLE_AIM_ASSIST_KEYBOARD = ENABLE_AIM_ASSIST_KEYBOARD;
        this.DROP_ITEM_MAX_NUM = DROP_ITEM_MAX_NUM;
        this.DROP_ITEM_MAX_NUM_UNKO = DROP_ITEM_MAX_NUM_UNKO;
        this.BASE_CAMP_MAX_NUM = BASE_CAMP_MAX_NUM;
        this.BASE_CAMP_WORKER_MAX_NUM = BASE_CAMP_WORKER_MAX_NUM;
        this.DROP_ITEM_ALIVE_MAX_HOURS = DROP_ITEM_ALIVE_MAX_HOURS;
        this.AUTO_RESET_GUILD_NO_ONLINE_PLAYERS = AUTO_RESET_GUILD_NO_ONLINE_PLAYERS;
        this.AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS = AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS;
        this.GUILD_PLAYER_MAX_NUM = GUILD_PLAYER_MAX_NUM;
        this.PAL_EGG_DEFAULT_HATCHING_TIME = PAL_EGG_DEFAULT_HATCHING_TIME;
        this.WORK_SPEED_RATE = WORK_SPEED_RATE;
        this.IS_MULTIPLAY = IS_MULTIPLAY;
        this.IS_PVP = IS_PVP;
        this.CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP = CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP;
        this.ENABLE_NON_LOGIN_PENALTY = ENABLE_NON_LOGIN_PENALTY;
        this.ENABLE_FAST_TRAVEL = ENABLE_FAST_TRAVEL;
        this.IS_START_LOCATION_SELECT_BY_MAP = IS_START_LOCATION_SELECT_BY_MAP;
        this.EXIST_PLAYER_AFTER_LOGOUT = EXIST_PLAYER_AFTER_LOGOUT;
        this.ENABLE_DEFENSE_OTHER_GUILD_PLAYER = ENABLE_DEFENSE_OTHER_GUILD_PLAYER;
        this.COOP_PLAYER_MAX_NUM = COOP_PLAYER_MAX_NUM;
        this.REGION = REGION;
        this.USEAUTH = USEAUTH;
        this.BAN_LIST_URL = BAN_LIST_URL;
        this.SHOW_PLAYER_LIST = SHOW_PLAYER_LIST;
    }

    public static PalworldOption initPalworldOption(Integer slot){
        return PalworldOption.builder()
                .PUID(1000)
                .PGID(1000)
                .PORT(8211)
                .PLAYERS(slot)
                .SERVER_PASSWORD("password")
                .MULTITHREADING(true)
                .RCON_ENABLED(true)
                .RCON_PORT(25575)
                .COMMUNITY(false)
                .SERVER_NAME("Palworld")
                .SERVER_DESCRIPTION("")
                .build();
    }

    public PalworldOption(int player){
        this.PLAYERS = player;
    }
}
